# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rimney <rimney@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/09 17:17:16 by rimney            #+#    #+#              #
#    Updated: 2022/11/09 17:21:42 by rimney           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Towards_a_more_useful_fixed-point_number_class
SRCS = fixed.cpp main.cpp
FLAGS = -Wall -Wextra -Werror  -std=c++98

all :
	c++ $(FLAGS) $(SRCS) -o $(NAME)	
clean :
	rm -f $(NAME)
fclean :
	rm -f $(NAME)
re : fclean all