# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rimney <rimney@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/25 22:21:20 by rimney            #+#    #+#              #
#    Updated: 2022/09/27 01:26:17 by rimney           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Phonebook
SRCS = phonebook.cpp
FLAGS = -Wall -Wextra -Werror -std=c++98

all :
	c++ $(FLAGS) $(SRCS) -o $(NAME)
clean:
	rm -f $(NAME)
fclean:
	rm -f $(NAME)
re : fclean all